---
name: Enable SSL for a domain on GoDaddy cPanel

on:
  workflow_dispatch:
    inputs:
      domain:
        description: "Domain name"
        required: true
        type: string
        default: "example.com"
      path:
        description: "Path to the domains hosting directory"
        required: true
        type: string
        default: "~/public_html/example.com"

jobs:
  ssl-setup:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSL with acme.sh
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # Check for acme.sh installation
            if ! command -v acme.sh &> /dev/null; then
              echo "::error::acme.sh is not installed"
              exit 1  
            fi

            # Issue staging certificate
            echo "::group::Issuing staging certificate"
            acme.sh --issue \
              --webroot "${{ inputs.path }}" \
              -d "${{ inputs.domain }}" \
              -d "www.${{ inputs.domain }}" \
              --staging || { echo "::error::Staging certificate failed"; exit 1; }
            echo "::endgroup::"

            # Issue production certificate
            echo "::group::Issuing production certificate"
            acme.sh --issue \
              --webroot "${{ inputs.path }}" \
              -d "${{ inputs.domain }}" \
              -d "www.${{ inputs.domain }}" \
              --force || { echo "::error::Production certificate failed"; exit 1; }
            echo "::endgroup::"

            # Deploy certificate
            echo "::group::Deploying certificate"
            acme.sh --deploy \
              --deploy-hook cpanel_uapi \
              --domain "${{ inputs.domain }}" || { echo "::error::Deployment failed"; exit 1; }
            echo "::endgroup::"
